"""add profissional_id to pacientes

Revision ID: 0847577a7792
Revises: de86dbaaa645
Create Date: 2026-03-24 19:45:24.915731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0847577a7792'
down_revision: Union[str, Sequence[str], None] = 'de86dbaaa645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_intervencoes_paciente_data'), table_name='intervencoes')
    op.drop_index(op.f('ix_intervencoes_paciente_data'), table_name='intervencoes')
    op.create_index(op.f('ix_profissionais_id'), 'profissionais', ['id'], unique=False)
    op.drop_constraint(op.f('uq_registro_paciente_data'), 'registros_diarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_registro_paciente_data'), 'registros_diarios', ['paciente_id', 'data'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_profissionais_id'), table_name='profissionais')
    op.create_index(op.f('ix_intervencoes_paciente_data'), 'intervencoes', ['paciente_id', sa.literal_column('data_intervencao DESC')], unique=False)
    op.create_index(op.f('idx_intervencoes_paciente_data'), 'intervencoes', ['paciente_id', sa.literal_column('data_intervencao DESC')], unique=False)
    # ### end Alembic commands ###
