"""Frozen Gate A economic foundation. No seed, backfill or clinical changes."""
from alembic import op
import sqlalchemy as sa

revision = 'f1_economia_v1'
down_revision = 'g2c1_autorizacao_v1'
branch_labels = None
depends_on = None

TABLES = ['servicos_economicos', 'tabelas_preco', 'tabela_preco_versoes', 'precos_servico', 'contratos_financeiros', 'paciente_contratos', 'mapeamentos_agenda_servico']
FUNCTIONS = ['f1_guard_truncate', 'f1_guard_table_identity', 'f1_guard_version', 'f1_guard_price', 'f1_guard_service', 'f1_guard_mapping', 'f1_guard_contract']
DDL = [
    """CREATE TABLE servicos_economicos (
	codigo VARCHAR(64) NOT NULL,
	descricao TEXT NOT NULL,
	ocupacao_id INTEGER NOT NULL,
	duracao_minutos INTEGER NOT NULL,
	tipo_atendimento VARCHAR(16) DEFAULT 'INDIVIDUAL' NOT NULL,
	unidade VARCHAR(16) DEFAULT 'SESSAO' NOT NULL,
	ativo BOOLEAN DEFAULT true NOT NULL,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_servico_economico_codigo UNIQUE (codigo),
	CONSTRAINT ck_servico_economico_texto CHECK (length(trim(codigo)) > 0 AND length(trim(descricao)) > 0),
	CONSTRAINT ck_servico_economico_duracao CHECK (duracao_minutos > 0),
	CONSTRAINT ck_servico_economico_unidade CHECK (tipo_atendimento = 'INDIVIDUAL' AND unidade = 'SESSAO'),
	FOREIGN KEY(ocupacao_id) REFERENCES ocupacoes_profissionais (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE tabelas_preco (
	proprietario_instituicao_id INTEGER NOT NULL,
	codigo VARCHAR(64) NOT NULL,
	nome TEXT NOT NULL,
	moeda VARCHAR(3) DEFAULT 'BRL' NOT NULL,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_tabela_preco_codigo UNIQUE (proprietario_instituicao_id, codigo),
	CONSTRAINT ck_tabela_preco_texto CHECK (length(trim(codigo)) > 0 AND length(trim(nome)) > 0),
	CONSTRAINT ck_tabela_preco_moeda CHECK (moeda = 'BRL'),
	FOREIGN KEY(proprietario_instituicao_id) REFERENCES instituicoes (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE tabela_preco_versoes (
	tabela_id BIGINT NOT NULL,
	numero INTEGER NOT NULL,
	vigente_desde DATE NOT NULL,
	estado VARCHAR(16) DEFAULT 'DRAFT' NOT NULL,
	publicado_em TIMESTAMP WITH TIME ZONE,
	publicado_por_usuario_id INTEGER,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_tabela_preco_versao_numero UNIQUE (tabela_id, numero),
	CONSTRAINT ck_tabela_preco_versao_numero CHECK (numero > 0),
	CONSTRAINT ck_tabela_preco_versao_publicacao CHECK ((estado = 'DRAFT' AND publicado_em IS NULL AND publicado_por_usuario_id IS NULL) OR (estado = 'PUBLISHED' AND publicado_em IS NOT NULL AND publicado_por_usuario_id IS NOT NULL)),
	FOREIGN KEY(tabela_id) REFERENCES tabelas_preco (id) ON DELETE RESTRICT,
	FOREIGN KEY(publicado_por_usuario_id) REFERENCES usuarios (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE precos_servico (
	versao_id BIGINT NOT NULL,
	servico_id BIGINT NOT NULL,
	valor_base NUMERIC(14, 2) NOT NULL,
	codigo_externo VARCHAR(128),
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_preco_servico UNIQUE (versao_id, servico_id),
	CONSTRAINT ck_preco_servico_valor CHECK (valor_base >= 0 AND valor_base::text NOT IN ('NaN', 'Infinity', '-Infinity')),
	CONSTRAINT ck_preco_servico_codigo CHECK (codigo_externo IS NULL OR length(trim(codigo_externo)) > 0),
	FOREIGN KEY(versao_id) REFERENCES tabela_preco_versoes (id) ON DELETE RESTRICT,
	FOREIGN KEY(servico_id) REFERENCES servicos_economicos (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE contratos_financeiros (
	pagador_instituicao_id INTEGER NOT NULL,
	codigo VARCHAR(64) NOT NULL,
	edicao INTEGER NOT NULL,
	tabela_preco_id BIGINT NOT NULL,
	inicio DATE NOT NULL,
	fim DATE,
	estado VARCHAR(16) DEFAULT 'DRAFT' NOT NULL,
	publicado_em TIMESTAMP WITH TIME ZONE,
	publicado_por_usuario_id INTEGER,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_contrato_financeiro_edicao UNIQUE (pagador_instituicao_id, codigo, edicao),
	CONSTRAINT ck_contrato_financeiro_codigo CHECK (edicao > 0 AND length(trim(codigo)) > 0),
	CONSTRAINT ck_contrato_financeiro_periodo CHECK (fim IS NULL OR fim >= inicio),
	CONSTRAINT ck_contrato_financeiro_publicacao CHECK ((estado = 'DRAFT' AND publicado_em IS NULL AND publicado_por_usuario_id IS NULL) OR (estado = 'PUBLISHED' AND publicado_em IS NOT NULL AND publicado_por_usuario_id IS NOT NULL)),
	FOREIGN KEY(pagador_instituicao_id) REFERENCES instituicoes (id) ON DELETE RESTRICT,
	FOREIGN KEY(tabela_preco_id) REFERENCES tabelas_preco (id) ON DELETE RESTRICT,
	FOREIGN KEY(publicado_por_usuario_id) REFERENCES usuarios (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE paciente_contratos (
	paciente_id INTEGER NOT NULL,
	contrato_id BIGINT NOT NULL,
	inicio DATE NOT NULL,
	fim DATE,
	identificador_beneficiario VARCHAR(128),
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT ck_paciente_contrato_periodo CHECK (fim IS NULL OR fim >= inicio),
	CONSTRAINT ck_paciente_contrato_identificador CHECK (identificador_beneficiario IS NULL OR length(trim(identificador_beneficiario)) > 0),
	CONSTRAINT ex_paciente_contrato_periodo EXCLUDE USING gist (paciente_id WITH =, contrato_id WITH =, daterange(inicio, fim, '[]') WITH &&),
	FOREIGN KEY(paciente_id) REFERENCES pacientes (id) ON DELETE RESTRICT,
	FOREIGN KEY(contrato_id) REFERENCES contratos_financeiros (id) ON DELETE RESTRICT
)""",
    """CREATE TABLE mapeamentos_agenda_servico (
	agenda_cuidado_id INTEGER NOT NULL,
	servico_id BIGINT NOT NULL,
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	criado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_mapeamento_agenda_servico UNIQUE (agenda_cuidado_id),
	FOREIGN KEY(agenda_cuidado_id) REFERENCES agenda_cuidados (id) ON DELETE RESTRICT,
	FOREIGN KEY(servico_id) REFERENCES servicos_economicos (id) ON DELETE RESTRICT
)""",
    """CREATE INDEX ix_servicos_economicos_ocupacao_id ON servicos_economicos (ocupacao_id)""",
    """CREATE UNIQUE INDEX uq_tabela_preco_versao_vigencia ON tabela_preco_versoes (tabela_id, vigente_desde) WHERE estado = 'PUBLISHED'""",
    """CREATE INDEX ix_precos_servico_servico_id ON precos_servico (servico_id)""",
    """CREATE UNIQUE INDEX uq_preco_servico_externo ON precos_servico (versao_id, codigo_externo) WHERE codigo_externo IS NOT NULL""",
    """CREATE INDEX ix_contratos_financeiros_tabela_preco_id ON contratos_financeiros (tabela_preco_id)""",
    """CREATE INDEX ix_paciente_contratos_contrato_id ON paciente_contratos (contrato_id)""",
    """CREATE INDEX ix_paciente_contratos_paciente_id ON paciente_contratos (paciente_id)""",
    """CREATE INDEX ix_mapeamentos_agenda_servico_servico_id ON mapeamentos_agenda_servico (servico_id)""",
]
GUARDS = """CREATE FUNCTION public.f1_guard_truncate() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'F1_TRUNCATE_FORBIDDEN' USING ERRCODE='23514', CONSTRAINT='f1_truncate_forbidden';
END $$;

CREATE FUNCTION public.f1_guard_table_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF (NEW.proprietario_instituicao_id,NEW.codigo,NEW.moeda) IS DISTINCT FROM (OLD.proprietario_instituicao_id,OLD.codigo,OLD.moeda) THEN
  RAISE EXCEPTION 'TABLE_IDENTITY_IMMUTABLE' USING ERRCODE='23514', CONSTRAINT='f1_table_identity';
 END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION public.f1_guard_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP <> 'INSERT' AND OLD.estado='PUBLISHED' THEN
  RAISE EXCEPTION 'PUBLISHED_IMMUTABLE' USING ERRCODE='23514', CONSTRAINT='f1_version_immutable';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 IF TG_OP='INSERT' AND NEW.estado<>'DRAFT' THEN
  RAISE EXCEPTION 'EXPLICIT_PUBLICATION_REQUIRED' USING ERRCODE='23514', CONSTRAINT='f1_version_publication';
 END IF;
 IF NEW.estado='PUBLISHED' THEN
  PERFORM 1 FROM public.tabelas_preco WHERE id=NEW.tabela_id FOR UPDATE;
  IF NEW.vigente_desde < (clock_timestamp() AT TIME ZONE 'UTC')::date THEN
   RAISE EXCEPTION 'RETROACTIVE_PUBLICATION' USING ERRCODE='23514', CONSTRAINT='f1_version_retroactive';
  END IF;
  NEW.publicado_em := clock_timestamp();
 END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION public.f1_guard_price() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE old_id bigint; new_id bigint; r record;
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'F1_READ_COMMITTED_REQUIRED' USING ERRCODE='23514', CONSTRAINT='f1_read_committed';
 END IF;
 IF TG_OP<>'INSERT' THEN old_id:=OLD.versao_id; END IF;
 IF TG_OP<>'DELETE' THEN new_id:=NEW.versao_id; END IF;
 FOR r IN SELECT id,estado FROM public.tabela_preco_versoes WHERE id IN (old_id,new_id) ORDER BY id FOR UPDATE LOOP
  IF r.estado<>'DRAFT' THEN
   RAISE EXCEPTION 'PUBLISHED_PRICE_IMMUTABLE' USING ERRCODE='23514', CONSTRAINT='f1_price_immutable';
  END IF;
 END LOOP;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 PERFORM 1 FROM public.servicos_economicos WHERE id=NEW.servico_id FOR UPDATE;
 RETURN NEW;
END $$;

CREATE FUNCTION public.f1_guard_service() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_setting('transaction_isolation') <> 'read committed' THEN
  RAISE EXCEPTION 'F1_READ_COMMITTED_REQUIRED' USING ERRCODE='23514', CONSTRAINT='f1_read_committed';
 END IF;
 IF (NEW.codigo,NEW.ocupacao_id,NEW.duracao_minutos,NEW.tipo_atendimento,NEW.unidade)
 IS DISTINCT FROM (OLD.codigo,OLD.ocupacao_id,OLD.duracao_minutos,OLD.tipo_atendimento,OLD.unidade)
 AND (EXISTS(SELECT 1 FROM public.precos_servico WHERE servico_id=OLD.id)
      OR EXISTS(SELECT 1 FROM public.mapeamentos_agenda_servico WHERE servico_id=OLD.id)) THEN
  RAISE EXCEPTION 'SERVICE_IN_USE' USING ERRCODE='23514', CONSTRAINT='f1_service_in_use';
 END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION public.f1_guard_mapping() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM 1 FROM public.servicos_economicos WHERE id=NEW.servico_id FOR UPDATE;
 RETURN NEW;
END $$;

CREATE FUNCTION public.f1_guard_contract() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE owner_id integer;
BEGIN
 IF TG_OP<>'INSERT' AND OLD.estado='PUBLISHED' THEN
  RAISE EXCEPTION 'PUBLISHED_IMMUTABLE' USING ERRCODE='23514', CONSTRAINT='f1_contract_immutable';
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 SELECT proprietario_instituicao_id INTO owner_id FROM public.tabelas_preco WHERE id=NEW.tabela_preco_id FOR SHARE;
 IF owner_id IS NOT NULL AND owner_id<>NEW.pagador_instituicao_id THEN
  RAISE EXCEPTION 'PAYER_TABLE_MISMATCH' USING ERRCODE='23514', CONSTRAINT='f1_contract_payer';
 END IF;
 IF TG_OP='INSERT' AND NEW.estado<>'DRAFT' THEN
  RAISE EXCEPTION 'EXPLICIT_PUBLICATION_REQUIRED' USING ERRCODE='23514', CONSTRAINT='f1_contract_publication';
 END IF;
 IF NEW.estado='PUBLISHED' THEN NEW.publicado_em:=clock_timestamp(); END IF;
 RETURN NEW;
END $$;"""


def upgrade():
    c = op.get_bind()
    if not c.execute(sa.text("SELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname='btree_gist')")).scalar():
        raise RuntimeError('F1_BTREE_GIST_REQUIRED')
    c.execute(sa.text('SET LOCAL search_path TO public'))
    for statement in DDL:
        c.execute(sa.text(statement))
    c.execute(sa.text(GUARDS))
    for table in TABLES:
        c.execute(sa.text(f'CREATE TRIGGER f1_no_truncate BEFORE TRUNCATE ON public.{table} FOR EACH STATEMENT EXECUTE FUNCTION public.f1_guard_truncate()'))
    guards = [
        ('tabelas_preco', 'UPDATE', 'f1_guard_table_identity'),
        ('tabela_preco_versoes', 'INSERT OR UPDATE OR DELETE', 'f1_guard_version'),
        ('precos_servico', 'INSERT OR UPDATE OR DELETE', 'f1_guard_price'),
        ('servicos_economicos', 'UPDATE', 'f1_guard_service'),
        ('mapeamentos_agenda_servico', 'INSERT OR UPDATE', 'f1_guard_mapping'),
        ('contratos_financeiros', 'INSERT OR UPDATE OR DELETE', 'f1_guard_contract'),
    ]
    for table, events, function in guards:
        c.execute(sa.text(f'CREATE TRIGGER {function} BEFORE {events} ON public.{table} FOR EACH ROW EXECUTE FUNCTION public.{function}()'))


def downgrade():
    c = op.get_bind()
    if c.execute(sa.text('SHOW transaction_isolation')).scalar() != 'read committed':
        raise RuntimeError('F1_DOWNGRADE_READ_COMMITTED_REQUIRED')
    c.execute(sa.text('LOCK TABLE ' + ','.join('public.'+t for t in TABLES) + ' IN ACCESS EXCLUSIVE MODE'))
    for table in TABLES:
        if c.execute(sa.text(f'SELECT EXISTS(SELECT 1 FROM public.{table})')).scalar():
            raise RuntimeError('F1_DOWNGRADE_BLOCKED_DATA')
    for table in reversed(TABLES):
        op.drop_table(table, schema='public')
    for function in FUNCTIONS:
        c.execute(sa.text(f'DROP FUNCTION public.{function}()'))
